services:
  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "6001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Database: "MGVjFy6QSHXki3MRcapeQPbUfCB2kXjCtnmqTrvzIvFM1e9M6YLJeFDVyuwKz3tJE/ebK95OmnDGj5tbBjsigP5EpVioYaafYVQZn0B5Xf2vBZgJRZ4GqmmR9v6a6iIGmvmL/FxtVrrVaxbyWlj45w=="
      ConnectionStrings__Redis: "redis:6379"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__VirtualHost: "/"
    networks:
      - ecommerce

networks:
  ecommerce:
    external: true
